services:
  app:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: listing_task_app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    links:
      - mysql
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - listing_task

  mysql:
    image: mysql:8.0.23
    container_name: listing_task_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - listing_task

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: listing_task_phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - listing_task

networks:
  listing_task:
    driver: bridge
