services:
  app:
    image: yiisoftware/yii2-php:7.4-apache
    env_file:
      - .env
    container_name: ${APP_CONTAINER_NAME}
    volumes:
      - ${APP_COMPOSER_CACHE}:/root/.composer/cache:delegated
      - ${APP_DIR}:/app:delegated
    links:
      - mysql
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - mysql
    networks:
      - listing_task

  mysql:
    image: mysql:8.0.23
    env_file:
      - .env
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ${DB_DATA_DIR}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      listing_task:
        aliases:
          - ${DB_HOST}


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    container_name: ${DB_ADMIN_CONTAINER_NAME}
    restart: always
    links:
      - mysql
    ports:
      - "${DB_ADMIN_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
    depends_on:
      - mysql
    networks:
      - listing_task

networks:
  listing_task:
    driver: bridge
