#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';

$config = new codemix\yii2confload\Config(__DIR__);

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$application = new yii\console\Application($config->console());
$exitCode = $application->run();
exit($exitCode);
